### ISSUE TITLE
Thoughts on updating this package to work with the latest GPflow?

### ISSUE THREAD

**Issue by Cyberface** [sremes/nssm-gp#3]
Hi, I recently came across your papers and this package and the work is really cool.

Do you have any plans on updating this package to work with the latest gpflow?

**Comment by sremes** [comment]
Unfortunately, I think it's quite unlikely that I will have time to update to the latest version of gpflow, haven't been using that recently.

**Comment by Cyberface** [comment]
No worries, thanks for letting me know - I had a little go at translating various lines to the latest gpflow however, I'm not an expert in it so might not get very far. If I do I will write back here.

Cheers!
